### ISSUE TITLE
The URL for example Authentication in Node.js application isn't correct

### ISSUE THREAD

**Issue by ahrtr** [oracle/idm-samples#21]
One of the links in the following page is "Use SDK for Authentication in Node.js Web Applications", 

> https://docs.oracle.com/en/cloud/paas/identity-cloud/index.html

But the link isn't correct, what's the correct URL of example for Authentication in Node.js?

Thanks!

**Comment by blitsz01** [comment]
Is it the reason why the example is pull out? The problem i have in the sample node.js is, When I click the oracle auth. It gives me bad gateway. When deploy in localhost the programs works just fine but when It is deploy in application cloud container it gives me badgateway error.

**Comment by faonbr** [comment]
Python and Node.js SDK related content have been pulled out due to issues found in the SDK for these languages. Expect them to be added soon.
