### ISSUE TITLE
idcs-sdk-sample-apps/java logout can't work as expected

### ISSUE THREAD

**Issue by emmansun** [oracle/idm-samples#25]
After i click my homepage **Log Out** link, IDCS just redirect me to IDCS login page, but not my specified post log out redirect url.

According [Using OpenID Connect for Log Out](https://docs.oracle.com/en/cloud/paas/identity-cloud/rest-api/logoutopenidconnect.html), i added **post_logout_redirect_uri** and **id_token_hint** to the **LogoutServlet** logoutURL, but it still did not work as expected.

After further checking the **SDK Web Application** configuration of logout url, i found that the logout url is used for clean application side session, so i created another **LogoutCallbackServlet** and it just performs session invalid job. Then i changed **SDK Web Application** logout url to new URL.

![image](https://user-images.githubusercontent.com/7235232/42925449-ccc91cb8-8b60-11e8-8202-43fa46044678.png)

It worked as expected now.

1.User click client application's Log Out link, and then trigger IDCS's logut invocation;
2.IDCS will call the log out url specified in **SDK Web Application** to terminate the resource owner's session;
3.Finally redirect to post log out redirect URL.

**Comment by faonbr** [comment]
Hi Sun Yimin, The sample app was not configure to return the user browser to its index nor login page.
Nice catch you had about how to configure it.

**Comment by faonbr** [comment]
Hi Sun Yimin,
I have updated the sample application and added the post logout feature.
If you update the sample app code, you'll see it in action.
Thanks for the tip.

**Comment by faonbr** [comment]
Hi Sun Yimin,
I have updated the sample application and added the post logout feature.
If you update the sample app code, you'll see it in action.
Thanks for the tip.

**Comment by faonbr** [comment]
Hi Sun Yimin,
I have updated the sample application and added the post logout feature.
If you update the sample app code, you'll see it in action.
Thanks for the tip.
