### ISSUE TITLE
Java SDK extension issue when we need to fetch user custom schema value in profile

### ISSUE THREAD

**Issue by emmansun** [oracle/idm-samples#28]
We defined our own custom schema for user profile, but when we use JAVA SDK , we found that it's hard to extend SDK's implementation IDCSUserManagerImpl.java.

1. The **userAttributes** are fixed and can't be passed with external env.
```
Constants.USER_ATTRIBUTES
public static String USER_ATTRIBUTES = "username,displayname,emails,groups,urn:ietf:params:scim:schemas:oracle:idcs:extension:user:User:appRoles";
...
conn.setRequestProperty(Constants.HEADER_AUTHORIZATION, String.format(Constants.AUTH_BEARER, accessToken));
```

2. When i try to implement our own **IDCSUserManager** implementation, we found the getUser method is private

`private JSONObject getUser(String userId, String accessToken) throws UnsupportedEncodingException, ProtocolException, MalformedURLException, IOException, ParseException
`
  
And the class **OAuthAccessTokenManagerImpl**'s constructor is package level, but not public.
So if i need to implement our own **IDCSUserManager** implementation, we can't extends IDCSUserManagerImpl due to getUser() is private, we had to implement **IDCSUserManager** all methods, and we can't use  **OAuthAccessTokenManagerImpl**, except we define our own implementation's package same as  **OAuthAccessTokenManagerImpl**'s: **oracle.security.jps.idcsbinding.shared** .

I do not know if it's suitable place to record this issue.

**Comment by faonbr** [comment]
Thank you for your feedback. As this is something in the SDK not in the sample app I'll send this feedback to engineers.
You can comment and provide feedback here, no problem. Every feedback counts.

**Comment by faonbr** [comment]
Hi. The Java SDK sample app has been updated. You no longer use the IDCSUserManager class.
