### ISSUE TITLE
No requirement.txt file in idcs-sdk-sample-apps/python

### ISSUE THREAD

**Issue by varunyn** [oracle/idm-samples#31]
In readme is says to install the required package run pip install -r requirement.txt but there is no file in sample-app.zip file

**Comment by faonbr** [comment]
Hi Varunyn, 
the doc state: "Open the **SDK zip** file, extract both README.txt and requirements.txt to a temporary folder, and run the following command line to install the required third-party libraries".

The SDK zip file you download from IDCS contains both readme and requirements text files.
